# ============================================================
#  Luban Build Configuration
#  Edit this file to change paths and build parameters.
#  Lines starting with # or ; are ignored.
#  Do NOT put spaces around the = sign.
# ============================================================

[paths]
luban_dll=../../Tools/DataTable/Luban/Luban.dll
client_code_out=../../UnityStarter/Assets/UnityStarter/Scripts/Generated/DataTable/
client_data_out=..././UnityStarter/Assets/StreamingAssets/DataTable/
server_code_out=../../DataTable/Luban/Generated/Server/Code/
server_data_out=../../DataTable/Luban/Generated/Server/Data/
all_code_out=../../DataTable/Luban/Generated/All/Code/
all_data_out=../../DataTable/Luban/Generated/All/Data/

[templates]
custom_template_dir=
bridge_files=

[build]
target=client
code_target=cs-bin
data_target=bin
clean_output=true
clean_orphan_meta=true
line_ending=crlf

[codegen]
codegen_project=../../UnityStarter/Assets/ThirdParty/CycloneGames/CycloneGames.DataTable/Tools~/CodeGen/CycloneGames.DataTable.CodeGen.csproj
string_constant_tables=
string_constant_value_column=name
string_constant_comment_column=comment
string_constant_enabled_column=enabled
string_constant_scope_column=scope
string_constant_generated_comment_language=en
