// luban.conf

{
    "groups": [
        {"names":["c"], "default":true},
        {"names":["s"], "default":false}
    ],
    "schemaFiles": [
        {"fileName":"Defines", "type":""},
        {"fileName":"Datas/__tables__.xlsx", "type":"table"},
        {"fileName":"Datas/__beans__.xlsx", "type":"bean"},
        {"fileName":"Datas/__enums__.xlsx", "type":"enum"}
    ],
    "dataDir": "Datas",
    "targets": [
        {"name":"client", "manager":"Tables", "groups":["c"], "topModule":"UnityStarter.GameConfig"},
        {"name":"server", "manager":"Tables", "groups":["s"], "topModule":"UnityStarter.GameConfig"},
        {"name":"all", "manager":"Tables", "groups":["c", "s"], "topModule":"UnityStarter.GameConfig"}
    ]
}
